export enum PlaceOfCode {
    Telehealth_Not_Patient_Home = "Telehealth- Not Patient\'s Home (02)",
    School = "School(03)",
    Homeless_Shelter = "Homeless Shelter(04)",
    Prison_Correctional_Fac = "Prison - Correctional Fac(09)",
    Telehealth_Patient_home = "Telehealth - Patient\'s home (10)",
    Office = "Office(11)",
    Home = "Home(12)",
    Assisted_Living_Facility = "Assisted Living Facility(13)",
    Group_Home = "Group Home(14)",
    Mobile_Unit = "Mobile Unit(15)",
    Temporary_Lodging = "Temporary Lodging(16)",
    Off_Campus_Outpatient_Hospital = "Off Campus - Outpatient Hospital(19)",
    Hospital = "Hospital(21)",
    Outpatient_Hospital = "Outpatient Hospital(22)",
    Military_Treatment_Facility = "Military Treatment Facility(26)",
    Skilled_Nursing_Facility = "Skilled Nursing Facility(31)",
    Nursing_Facility = "Nursing Facility(32)",
    Hospice = "Hospice(34)",
    Independent_Clinic = "Independent Clinic(49)",
    Community_Mental_Health_Center = "Community Mental Health Center(53)",
    Outpatient_Rehab = "Outpatient Rehab(62)",
    Other_Setting = "Other Setting(99)"
}